---
######################################################################
# 1) Аргентина: ставим node_exporter как systemd-сервис
######################################################################
- name: Install node_exporter on Argentina nodes
  hosts: argentina
  become: yes
  tasks:
    - name: Create /opt/node_exporter directory
      file:
        path: /opt/node_exporter
        state: directory
        mode: "0755"

    - name: Download node_exporter tarball
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
        dest: /opt/node_exporter/node_exporter.tar.gz
        mode: "0644"

    - name: Extract node_exporter
      unarchive:
        src: /opt/node_exporter/node_exporter.tar.gz
        dest: /opt/node_exporter
        remote_src: yes
        creates: /opt/node_exporter/node_exporter-1.8.1.linux-amd64

    - name: Install node_exporter binary
      copy:
        src: /opt/node_exporter/node_exporter-1.8.1.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        remote_src: yes
        mode: "0755"

    - name: Install systemd service for node_exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        mode: "0644"
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start node_exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes


######################################################################
# 2) Мониторинг-нода (mon1): Docker + Prometheus + Alertmanager + Grafana
######################################################################
- name: Install Prometheus + Alertmanager + Grafana on monitoring node
  hosts: monitoring
  become: yes
  tasks:
    - name: Make sure broken docker.list is removed
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Install base deps
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Ensure keyrings directory exists
      file:
        path: /usr/share/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker.gpg
        mode: "0644"

    - name: Add Docker APT repository (correct, без $(...))
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        mode: "0644"
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

    - name: apt update after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker engine and compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create monitoring directories
      file:
        path: "/opt/monitoring/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - ""
        - prometheus
        - alertmanager
        - grafana

    - name: Write docker-compose.yml for monitoring stack
      copy:
        dest: /opt/monitoring/docker-compose.yml
        mode: "0644"
        content: |
          version: "3.8"

          services:
            prometheus:
              image: prom/prometheus
              container_name: prometheus
              volumes:
                - ./prometheus:/etc/prometheus
              ports:
                - "9090:9090"
              restart: unless-stopped

            alertmanager:
              image: prom/alertmanager
              container_name: alertmanager
              volumes:
                - ./alertmanager:/etc/alertmanager
              ports:
                - "9093:9093"
              restart: unless-stopped

            grafana:
              image: grafana/grafana
              container_name: grafana
              ports:
                - "3000:3000"
              volumes:
                - ./grafana:/var/lib/grafana
              restart: unless-stopped

    - name: Copy Prometheus config
      template:
        src: templates/prometheus.yml.j2
        dest: /opt/monitoring/prometheus/prometheus.yml
        mode: "0644"

    - name: Copy Alertmanager config
      copy:
        dest: /opt/monitoring/alertmanager/alertmanager.yml
        mode: "0644"
        content: |
          route:
            receiver: default

          receivers:
            - name: default
              webhook_configs:
                - url: http://localhost:5001/

    - name: Start monitoring stack via docker compose
      shell: docker compose up -d
      args:
        chdir: /opt/monitoring