{
 "title": "YugabyteDB - 3 Nodes Cluster (Separate Metrics)",
 "tags": [
  "yugabytedb",
  "cluster",
  "3nodes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Node 1 - YugabyteDB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node 1 - Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node1\"}[1m]))",
     "legendFormat": "Read IOPS"
    }
   ]
  },
  {
   "title": "Node 1 - Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node1\"}[1m]))",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Node 1 - Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(sum(irate(rpc_latency_sum{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node1\"}[1m])) / sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node1\"}[1m])))",
     "legendFormat": "Read Latency"
    }
   ]
  },
  {
   "title": "Node 1 - Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(sum(irate(rpc_latency_sum{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node1\"}[1m])) / sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node1\"}[1m])))",
     "legendFormat": "Write Latency"
    }
   ]
  },
  { "title": "Node 2 - YugabyteDB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node 2 - Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node2\"}[1m]))",
     "legendFormat": "Read IOPS"
    }
   ]
  },
  {
   "title": "Node 2 - Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node2\"}[1m]))",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Node 2 - Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(sum(irate(rpc_latency_sum{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node2\"}[1m])) / sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node2\"}[1m])))",
     "legendFormat": "Read Latency"
    }
   ]
  },
  {
   "title": "Node 2 - Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(sum(irate(rpc_latency_sum{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node2\"}[1m])) / sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node2\"}[1m])))",
     "legendFormat": "Write Latency"
    }
   ]
  },
  { "title": "Node 3 - YugabyteDB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Node 3 - Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node3\"}[1m]))",
     "legendFormat": "Read IOPS"
    }
   ]
  },
  {
   "title": "Node 3 - Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node3\"}[1m]))",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Node 3 - Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(sum(irate(rpc_latency_sum{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node3\"}[1m])) / sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"SelectStmt\", node=\"node3\"}[1m])))",
     "legendFormat": "Read Latency"
    }
   ]
  },
  {
   "title": "Node 3 - Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(sum(irate(rpc_latency_sum{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node3\"}[1m])) / sum(irate(rpc_latency_count{job=\"yugabytedb\", export_type=\"ysql_export\", server_type=\"yb_ysqlserver\", service_type=\"SQLProcessor\", service_method=\"InsertStmt\", node=\"node3\"}[1m])))",
     "legendFormat": "Write Latency"
    }
   ]
  }
 ]
}